- name: mysql configuration
  hosts:  mysql.robotshop.site
  become: yes
  tasks:  
    - name: install mysql
      ansible.builtin.package:
        name: mysql-server
        state:  present

    - name: enable and start service
      ansible.builtin.service:
        name: mysqld
        enabled:  yes
        state:  started

    - name: installing module PyMySQL
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - PyMySQL
        - cryptography

    - name: setting root pass
      ansible.builtin.command:  mysql_secure_installation --set-root-pass RoboShop@1
      
