- name: user component 
  hosts:  user
  become: yes
  tasks:
    - name: disable default version of nodejs
      ansible.builtin.command:  dnf module disable nodejs -y

    - name: enable the version which is required
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: installing nodejs
      ansible.builtin.package:
        name: nodejs
        state:  present

    - name: creating system user
      ansible.builtin.user:
        name: roboshop
        shell:  /sbin/nologin
        system: yes
        home: /app
        create_home:  yes
      
    - name: creating home directory app
      ansible.builtin.file:
        path: /app
        state:  directory

    - name: downloading application file
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip

    - name: unzipping the file content to /app directory
      ansible.builtin.unarchive:
        src:  /tmp/user.zip
        dest: /app
        remote_src: yes

    - name: changing directory to /app
      ansible.builtin.command:  cd /app

    - name: installing npm package in nodejs
      community.general.npm:
        path: /app

    - name: copying systemd service to desired path
      ansible.builtin.copy:
        src:  user.service
        dest: /etc/systemd/system/user.service
        

    - name: daemon reload in progress
      ansible.builtin.systemd_service:
        daemon_reload:  true

    - name: enable and start user service
      ansible.builtin.service:
        name: user
        enabled:  yes
        state:  started

   